language: node_js
node_js:
- "4.2"

before_script:
- chmod +x tests/tests.sh
- chmod +x deploy.sh

script:
- ./tests/tests.sh

deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app:
    master: alonzo
